name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate timestamp tag
        id: timestamp
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image for amd64 and arm64
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ptag/meteormail:latest \
            -t ptag/meteormail:${{ steps.timestamp.outputs.tag }} \
            . --push
